trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        mkdir "$(Build.SourcesDirectory)/dist"
        cp -r "$(Build.SourcesDirectory)/src/*" "$(Build.SourcesDirectory)/dist"
        cd "$(Build.SourcesDirectory)/dist"
        openssl genrsa -out key.pem 2048
        openssl rsa -in key.pem -outform DER -pubout -out public.pem
        zip -r extension.zip .
        node "$(Build.SourcesDirectory)/dist/generate-crx.js"
    displayName: 'Build and package extension'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'extension'
      pathtoPublish: '$(Build.SourcesDirectory)/dist/my-extension.crx'
    displayName: 'Publish extension artifact'
