name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the Bink...!!, we will work on this issue'' first issue'
        pr-message: 'Welcome to the Bink...!!, reviewer will get in touch with you shortly'' first pr'
